// packages/angular/src/lib/ui/compass.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input, output } from '@angular/core';
import { WwGlobeComponent } from '../globe.component';
import { WwPanelComponent, type WwPanelPosition } from './panel.component';

/** A compass rose that turns with the camera heading; click it to face north again.
 * @category Widgets
 */
@Component({
  selector: 'ww-compass',
  imports: [WwPanelComponent],
  template: `
    <ww-panel [position]="position()" class="wwui-compass-panel" [class]="panelClass()">
      <button
        type="button"
        class="wwui-compass"
        [style.width.px]="size()"
        [style.height.px]="size()"
        title="Reset to north"
        [attr.aria-label]="'Compass, heading ' + rounded() + ' degrees. Reset to north'"
        [attr.data-heading]="rounded()"
        (click)="onClick()"
      >
        <svg viewBox="0 0 100 100" class="wwui-compass__rose" [style.transform]="'rotate(' + -heading() + 'deg)'" aria-hidden="true" focusable="false">
          <circle cx="50" cy="50" r="46" class="wwui-compass__ring" />
          <line x1="86" y1="50" x2="92" y2="50" class="wwui-compass__tick" />
          <line x1="50" y1="86" x2="50" y2="92" class="wwui-compass__tick" />
          <line x1="8" y1="50" x2="14" y2="50" class="wwui-compass__tick" />
          <text x="50" y="23" text-anchor="middle" class="wwui-compass__label">N</text>
          <path d="M50 27 L59 50 L50 46 L41 50 Z" class="wwui-compass__north" />
          <path d="M50 73 L59 50 L50 54 L41 50 Z" class="wwui-compass__south" />
        </svg>
      </button>
    </ww-panel>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwCompassComponent {
  private readonly globeHost = inject(WwGlobeComponent);

  readonly position = input<WwPanelPosition>('top-right');
  /** Diameter in CSS pixels. */
  readonly size = input(56);
  /** Reset the heading to north when clicked. */
  readonly resetOnClick = input(true);
  /** Extra classes for the panel. */
  readonly panelClass = input<string>('');
  /** Emits the heading (degrees clockwise from north) that was showing when clicked. */
  readonly compassClick = output<number>();

  /** Heading in degrees, 0..360. */
  readonly heading = computed(() => {
    const heading = this.globeHost.cameraState()?.heading ?? 0;
    return ((heading % 360) + 360) % 360;
  });
  protected readonly rounded = computed(() => Math.round(this.heading()) % 360);

  protected onClick(): void {
    if (this.resetOnClick()) this.globeHost.globe()?.camera.resetNorth();
    this.compassClick.emit(this.heading());
  }
}

// packages/react/src/ui/Compass.tsx
import { useCamera } from '../hooks';
import { cx } from '../internal/utils';
import { Panel, type PanelPosition } from './Panel';

/** @category Widgets */
export interface CompassProps {
  position?: PanelPosition;
  /** Diameter in CSS pixels. Default 56. */
  size?: number;
  /** Reset the heading to north when clicked. Default true. */
  resetOnClick?: boolean;
  onClick?: (heading: number) => void;
  className?: string;
}

/** A compass rose that turns with the camera heading; click it to face north again.
 * @category Widgets
 */
export function Compass({ position = 'top-right', size = 56, resetOnClick = true, onClick, className }: CompassProps) {
  const { state, resetNorth } = useCamera();
  const heading = ((state.heading % 360) + 360) % 360;
  const rounded = Math.round(heading) % 360;
  return (
    <Panel position={position} className={cx('wwui-compass-panel', className)}>
      <button
        type="button"
        className="wwui-compass"
        style={{ width: size, height: size }}
        title="Reset to north"
        aria-label={`Compass, heading ${rounded} degrees. Reset to north`}
        data-heading={rounded}
        onClick={() => {
          if (resetOnClick) resetNorth();
          onClick?.(heading);
        }}
      >
        <svg viewBox="0 0 100 100" className="wwui-compass__rose" style={{ transform: `rotate(${-heading}deg)` }} aria-hidden="true" focusable="false">
          <circle cx="50" cy="50" r="46" className="wwui-compass__ring" />
          <line x1="86" y1="50" x2="92" y2="50" className="wwui-compass__tick" />
          <line x1="50" y1="86" x2="50" y2="92" className="wwui-compass__tick" />
          <line x1="8" y1="50" x2="14" y2="50" className="wwui-compass__tick" />
          <text x="50" y="23" textAnchor="middle" className="wwui-compass__label">
            N
          </text>
          <path d="M50 27 L59 50 L50 46 L41 50 Z" className="wwui-compass__north" />
          <path d="M50 73 L59 50 L50 54 L41 50 Z" className="wwui-compass__south" />
        </svg>
      </button>
    </Panel>
  );
}
