// packages/angular/src/lib/ui/goto-box.component.ts
import { ChangeDetectionStrategy, Component, inject, input, output, signal } from '@angular/core';
import {
  geocode,
  parseLatLon,
  rangeForBoundingBox,
  type CameraTarget,
  type GeocodeOptions,
  type GeocodeResult,
} from 'worldwind-kit';
import { WwGlobeComponent } from '../globe.component';
import { WwPanelComponent, type WwPanelPosition } from './panel.component';

type Status = { kind: 'idle' } | { kind: 'searching' } | { kind: 'empty' } | { kind: 'error'; message: string };

/** A search box: type `lat, lon` or a place name and fly there.
 * @category Widgets
 */
@Component({
  selector: 'ww-goto-box',
  imports: [WwPanelComponent],
  template: `
    <ww-panel [position]="position()" [heading]="heading()">
      <form class="wwui-goto" role="search" (submit)="submit($event)">
        <div class="wwui-goto__row">
          <input
            class="wwui-goto__input"
            type="search"
            [value]="query()"
            [placeholder]="placeholder()"
            aria-label="Go to location"
            (input)="query.set($any($event.target).value)"
          />
          <button type="submit" class="wwui-button wwui-goto__submit" [disabled]="status().kind === 'searching'">Go</button>
        </div>
        @switch (status().kind) {
          @case ('searching') {
            <div class="wwui-goto__status">Searching…</div>
          }
          @case ('empty') {
            <div class="wwui-goto__status">No results</div>
          }
          @case ('error') {
            <div class="wwui-goto__status" role="alert">{{ errorMessage() }}</div>
          }
        }
        @if (results().length > 0) {
          <ul class="wwui-goto__results">
            @for (result of results(); track $index) {
              <li>
                <button type="button" class="wwui-goto__result" (click)="choose(result)">{{ result.displayName }}</button>
              </li>
            }
          </ul>
        }
      </form>
    </ww-panel>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwGoToBoxComponent {
  private readonly globeHost = inject(WwGlobeComponent);

  readonly position = input<WwPanelPosition>('top-left');
  readonly heading = input<string | null>('Go to');
  readonly placeholder = input('City or "lat, lon"');
  /** Flight duration in ms. */
  readonly duration = input(2000);
  /** Range for typed coordinates and results without a bounding box. Default 200 km. */
  readonly defaultRange = input(200_000);
  /** Options for place-name search, or `false` to accept coordinates only. */
  readonly geocoding = input<GeocodeOptions | false>({});
  readonly navigated = output<{ target: CameraTarget; result?: GeocodeResult }>();

  protected readonly query = signal('');
  protected readonly results = signal<GeocodeResult[]>([]);
  protected readonly status = signal<Status>({ kind: 'idle' });
  private request = 0;

  protected errorMessage(): string {
    const status = this.status();
    return status.kind === 'error' ? status.message : '';
  }

  protected async submit(event: Event): Promise<void> {
    event.preventDefault();
    const query = this.query();
    const coordinates = parseLatLon(query);
    if (coordinates) {
      this.navigate({ ...coordinates, range: this.defaultRange() });
      return;
    }
    const geocoding = this.geocoding();
    if (geocoding === false || !query.trim()) return;
    const id = ++this.request;
    this.status.set({ kind: 'searching' });
    try {
      const found = await geocode(query, geocoding);
      if (id !== this.request) return;
      if (found.length === 0) {
        this.reset({ kind: 'empty' });
      } else if (found.length === 1) {
        this.choose(found[0]!);
      } else {
        this.show(found, { kind: 'idle' });
      }
    } catch (error) {
      if (id !== this.request) return;
      this.reset({ kind: 'error', message: error instanceof Error ? error.message : String(error) });
    }
  }

  protected choose(result: GeocodeResult): void {
    this.navigate(
      {
        latitude: result.latitude,
        longitude: result.longitude,
        range: result.boundingBox ? rangeForBoundingBox(result.boundingBox) : this.defaultRange(),
      },
      result,
    );
  }

  private show(results: GeocodeResult[], status: Status): void {
    this.results.set(results);
    this.status.set(status);
  }

  private reset(status: Status): void {
    this.show([], status);
  }

  private navigate(target: CameraTarget, result?: GeocodeResult): void {
    this.reset({ kind: 'idle' });
    this.navigated.emit(result ? { target, result } : { target });
    void this.globeHost.globe()?.camera.goTo(target, { duration: this.duration() });
  }
}

// packages/react/src/ui/GoToBox.tsx
import { useRef, useState, type FormEvent } from 'react';
import {
  geocode,
  parseLatLon,
  rangeForBoundingBox,
  type CameraTarget,
  type GeocodeOptions,
  type GeocodeResult,
} from 'worldwind-kit';
import { useGlobe } from '../context';
import { Panel, type PanelPosition } from './Panel';

/** @category Widgets */
export interface GoToBoxProps {
  position?: PanelPosition;
  heading?: string | null;
  placeholder?: string;
  /** Flight duration in ms. Default 2000. */
  duration?: number;
  /** Range used when a result has no bounding box, or for typed coordinates. Default 200 km. */
  defaultRange?: number;
  /** Options for place-name search, or `false` to accept coordinates only. */
  geocoding?: GeocodeOptions | false;
  onNavigate?: (target: CameraTarget, result?: GeocodeResult) => void;
  className?: string;
}

type Status = { kind: 'idle' } | { kind: 'searching' } | { kind: 'empty' } | { kind: 'error'; message: string };

/** A search box: type `lat, lon` or a place name and fly there.
 * @category Widgets
 */
export function GoToBox({
  position = 'top-left',
  heading = 'Go to',
  placeholder = 'City or "lat, lon"',
  duration = 2000,
  defaultRange = 200_000,
  geocoding = {},
  onNavigate,
  className,
}: GoToBoxProps) {
  const globe = useGlobe();
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<GeocodeResult[]>([]);
  const [status, setStatus] = useState<Status>({ kind: 'idle' });
  const request = useRef(0);

  const show = (found: GeocodeResult[], next: Status) => {
    setResults(found);
    setStatus(next);
  };
  const reset = (next: Status) => show([], next);

  const navigate = (target: CameraTarget, result?: GeocodeResult) => {
    reset({ kind: 'idle' });
    onNavigate?.(target, result);
    void globe.camera.goTo(target, { duration });
  };

  const choose = (result: GeocodeResult) => {
    navigate(
      {
        latitude: result.latitude,
        longitude: result.longitude,
        range: result.boundingBox ? rangeForBoundingBox(result.boundingBox) : defaultRange,
      },
      result,
    );
  };

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    const coordinates = parseLatLon(query);
    if (coordinates) {
      navigate({ ...coordinates, range: defaultRange });
      return;
    }
    if (geocoding === false || !query.trim()) return;
    const id = ++request.current;
    setStatus({ kind: 'searching' });
    try {
      const found = await geocode(query, geocoding);
      if (id !== request.current) return;
      if (found.length === 0) {
        reset({ kind: 'empty' });
      } else if (found.length === 1) {
        choose(found[0]!);
      } else {
        show(found, { kind: 'idle' });
      }
    } catch (error) {
      if (id !== request.current) return;
      reset({ kind: 'error', message: error instanceof Error ? error.message : String(error) });
    }
  };

  return (
    <Panel position={position} heading={heading} className={className}>
      <form className="wwui-goto" onSubmit={(event) => void submit(event)} role="search">
        <div className="wwui-goto__row">
          <input
            className="wwui-goto__input"
            type="search"
            value={query}
            placeholder={placeholder}
            aria-label="Go to location"
            onChange={(event) => setQuery(event.target.value)}
          />
          <button type="submit" className="wwui-button wwui-goto__submit" disabled={status.kind === 'searching'}>
            Go
          </button>
        </div>
        {status.kind === 'searching' ? <div className="wwui-goto__status">Searching…</div> : null}
        {status.kind === 'empty' ? <div className="wwui-goto__status">No results</div> : null}
        {status.kind === 'error' ? (
          <div className="wwui-goto__status" role="alert">
            {status.message}
          </div>
        ) : null}
        {results.length > 0 ? (
          <ul className="wwui-goto__results">
            {results.map((result, index) => (
              <li key={index}>
                <button type="button" className="wwui-goto__result" onClick={() => choose(result)}>
                  {result.displayName}
                </button>
              </li>
            ))}
          </ul>
        ) : null}
      </form>
    </Panel>
  );
}
