// packages/angular/src/lib/ui/layer-switcher.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { isInternalLayer, isOverlayLayer, type WWLayer } from 'worldwind-kit';
import { WwGlobeComponent } from '../globe.component';
import { WwPanelComponent, type WwPanelPosition } from './panel.component';

/** Checkboxes and opacity sliders for every layer on the globe.
 * @category Widgets
 */
@Component({
  selector: 'ww-layer-switcher',
  imports: [WwPanelComponent],
  template: `
    <ww-panel [position]="position()" [heading]="heading()">
      <ul class="wwui-layer-switcher">
        @for (layer of visibleLayers(); track layer) {
          <li class="wwui-layer-switcher__item">
            <label class="wwui-layer-switcher__label">
              <input type="checkbox" [checked]="layer.enabled" (change)="toggle(layer)" />
              <span>{{ layer.displayName }}</span>
            </label>
            @if (showOpacity()) {
              <input
                type="range"
                class="wwui-layer-switcher__opacity"
                min="0"
                max="1"
                step="0.05"
                [value]="layer.opacity"
                [attr.aria-label]="layer.displayName + ' opacity'"
                (input)="setOpacity(layer, $event)"
              />
            }
          </li>
        }
      </ul>
    </ww-panel>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwLayerSwitcherComponent {
  private readonly globeHost = inject(WwGlobeComponent);

  readonly position = input<WwPanelPosition>('top-left');
  readonly heading = input<string | null>('Layers');
  readonly showOpacity = input(true);
  /** Hide screen-space layers such as the compass, and layers owned by tools. */
  readonly hideOverlays = input(true);
  /** List the top-most layer first. */
  readonly topFirst = input(true);
  readonly filter = input<((layer: WWLayer) => boolean) | undefined>(undefined);

  protected readonly visibleLayers = computed(() => {
    const filter = this.filter();
    const hideOverlays = this.hideOverlays();
    const layers = this.globeHost
      .layers()
      .filter(
        (layer) => (!hideOverlays || (!isOverlayLayer(layer) && !isInternalLayer(layer))) && (!filter || filter(layer)),
      );
    return this.topFirst() ? layers.slice().reverse() : layers;
  });

  protected toggle(layer: WWLayer): void {
    this.globeHost.globe()?.layers.toggle(layer);
  }

  protected setOpacity(layer: WWLayer, event: Event): void {
    this.globeHost.globe()?.layers.setOpacity(layer, Number((event.target as HTMLInputElement).value));
  }
}

// packages/react/src/ui/LayerSwitcher.tsx
import { isInternalLayer, isOverlayLayer, type WWLayer } from 'worldwind-kit';
import { useGlobe } from '../context';
import { useLayers } from '../hooks';
import { layerKey } from '../internal/utils';
import { Panel, type PanelPosition } from './Panel';

/** @category Widgets */
export interface LayerSwitcherProps {
  position?: PanelPosition;
  heading?: string | null;
  /** Show an opacity slider under each layer. Default true. */
  showOpacity?: boolean;
  /** Hide screen-space layers such as the compass, and layers owned by tools. Default true. */
  hideOverlays?: boolean;
  /** List the top-most layer first. Default true. */
  topFirst?: boolean;
  filter?: (layer: WWLayer) => boolean;
  className?: string;
}

/** Checkboxes and opacity sliders for every layer on the globe.
 * @category Widgets
 */
export function LayerSwitcher({
  position = 'top-left',
  heading = 'Layers',
  showOpacity = true,
  hideOverlays = true,
  topFirst = true,
  filter,
  className,
}: LayerSwitcherProps) {
  const globe = useGlobe();
  const all = useLayers();
  let layers = all.filter(
    (layer) => (!hideOverlays || (!isOverlayLayer(layer) && !isInternalLayer(layer))) && (!filter || filter(layer)),
  );
  if (topFirst) layers = layers.slice().reverse();

  return (
    <Panel position={position} heading={heading} className={className}>
      <ul className="wwui-layer-switcher">
        {layers.map((layer) => {
          const id = layerKey(layer);
          return (
            <li key={id} className="wwui-layer-switcher__item">
              <label className="wwui-layer-switcher__label">
                <input type="checkbox" checked={layer.enabled} onChange={() => globe.layers.toggle(layer)} />
                <span>{layer.displayName}</span>
              </label>
              {showOpacity ? (
                <input
                  type="range"
                  className="wwui-layer-switcher__opacity"
                  min={0}
                  max={1}
                  step={0.05}
                  value={layer.opacity}
                  aria-label={`${layer.displayName} opacity`}
                  onChange={(event) => globe.layers.setOpacity(layer, Number(event.target.value))}
                />
              ) : null}
            </li>
          );
        })}
      </ul>
    </Panel>
  );
}
