// packages/react/src/ui/MeasureTool.tsx
import { formatArea, formatDistance, type MeasureToolOptions } from 'worldwind-kit';
import { useMeasureTool } from '../hooks';
import { cx } from '../internal/utils';
import { Panel, type PanelPosition } from './Panel';

/** @category Widgets */
export interface MeasureToolProps extends MeasureToolOptions {
  position?: PanelPosition;
  heading?: string | null;
  className?: string;
}

/** Click-to-measure distances and areas, with start/stop, undo and clear.
 * @category Widgets
 */
export function MeasureTool({ position = 'top-left', heading = 'Measure', className, ...options }: MeasureToolProps) {
  const { state, toggle, undo, clear } = useMeasureTool(options);
  const { points, lengthMeters, areaSquareMeters, active } = state;
  return (
    <Panel position={position} heading={heading} className={cx('wwui-measure', className)}>
      <div className="wwui-toolbar wwui-toolbar--horizontal" style={{ padding: 0 }} role="group" aria-label="Measure">
        <button
          type="button"
          className={cx('wwui-button', 'wwui-button--wide', active && 'wwui-button--active')}
          aria-pressed={active}
          onClick={toggle}
        >
          {active ? 'Stop' : 'Measure'}
        </button>
        <button type="button" className="wwui-button" title="Undo last point" aria-label="Undo last point" disabled={points.length === 0} onClick={undo}>
          ↶
        </button>
        <button type="button" className="wwui-button" title="Clear" aria-label="Clear measurement" disabled={points.length === 0} onClick={clear}>
          ✕
        </button>
      </div>
      <div className="wwui-coords" aria-live="polite">
        <span>
          <span className="wwui-coords__label">Points</span>
          {points.length}
        </span>
        <span>
          <span className="wwui-coords__label">Length</span>
          {formatDistance(lengthMeters)}
        </span>
        {areaSquareMeters !== null ? (
          <span>
            <span className="wwui-coords__label">Area</span>
            {formatArea(areaSquareMeters)}
          </span>
        ) : null}
      </div>
      <div className="wwui-goto__status">{active ? 'Click the globe to add points' : 'Press Measure, then click the globe'}</div>
    </Panel>
  );
}

// packages/angular/src/lib/ui/measure-tool.component.ts
import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, input, signal, untracked } from '@angular/core';
import {
  MeasureTool,
  formatArea,
  formatDistance,
  type MeasurementState,
  type PathType,
  type ShapeStyle,
} from 'worldwind-kit';
import { WwGlobeComponent } from '../globe.component';
import { WwPanelComponent, type WwPanelPosition } from './panel.component';

const IDLE: MeasurementState = { points: [], lengthMeters: 0, areaSquareMeters: null, active: false };

/** Click-to-measure distances and areas, with start/stop, undo and clear.
 * @category Widgets
 */
@Component({
  selector: 'ww-measure-tool',
  imports: [WwPanelComponent],
  template: `
    <ww-panel [position]="position()" [heading]="heading()" class="wwui-measure" [class]="panelClass()">
      <div class="wwui-toolbar wwui-toolbar--horizontal" style="padding: 0" role="group" aria-label="Measure">
        <button
          type="button"
          class="wwui-button wwui-button--wide"
          [class.wwui-button--active]="state().active"
          [attr.aria-pressed]="state().active"
          (click)="tool?.toggle()"
        >
          {{ state().active ? 'Stop' : 'Measure' }}
        </button>
        <button type="button" class="wwui-button" title="Undo last point" aria-label="Undo last point" [disabled]="state().points.length === 0" (click)="tool?.undo()">↶</button>
        <button type="button" class="wwui-button" title="Clear" aria-label="Clear measurement" [disabled]="state().points.length === 0" (click)="tool?.clear()">✕</button>
      </div>
      <div class="wwui-coords" aria-live="polite">
        <span><span class="wwui-coords__label">Points</span>{{ state().points.length }}</span>
        <span><span class="wwui-coords__label">Length</span>{{ length() }}</span>
        @if (state().areaSquareMeters !== null) {
          <span><span class="wwui-coords__label">Area</span>{{ area() }}</span>
        }
      </div>
      <div class="wwui-goto__status">{{ state().active ? 'Click the globe to add points' : 'Press Measure, then click the globe' }}</div>
    </ww-panel>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwMeasureToolComponent {
  private readonly globeHost = inject(WwGlobeComponent);

  readonly position = input<WwPanelPosition>('top-left');
  readonly heading = input<string | null>('Measure');
  readonly pathType = input<PathType | undefined>(undefined);
  readonly followTerrain = input<boolean | undefined>(undefined);
  readonly line = input<ShapeStyle | undefined>(undefined);
  /** Extra classes for the panel (the widget's host element renders nothing itself). */
  readonly panelClass = input<string>('');

  /** The tool, once the globe is ready. */
  tool: MeasureTool | null = null;
  protected readonly state = signal<MeasurementState>(IDLE);

  constructor() {
    effect((onCleanup) => {
      const globe = this.globeHost.globe();
      if (!globe) return;
      const tool = untracked(
        () => new MeasureTool(globe, { pathType: this.pathType(), followTerrain: this.followTerrain(), line: this.line() }),
      );
      this.tool = tool;
      this.state.set(tool.state);
      const unsubscribe = tool.subscribe((state) => this.state.set(state));
      onCleanup(() => {
        unsubscribe();
        tool.destroy();
        this.tool = null;
        this.state.set(IDLE);
      });
    });
    inject(DestroyRef).onDestroy(() => this.tool?.destroy());
  }

  protected length(): string {
    return formatDistance(this.state().lengthMeters);
  }

  protected area(): string {
    const area = this.state().areaSquareMeters;
    return area === null ? '' : formatArea(area);
  }
}
