// packages/react/src/ui/NavigationControls.tsx
import type { CameraTarget } from 'worldwind-kit';
import { cx } from '../internal/utils';
import { useCamera } from '../hooks';
import { Panel, type PanelPosition } from './Panel';

/** @category Widgets */
export interface NavigationControlsProps {
  position?: PanelPosition;
  orientation?: 'vertical' | 'horizontal';
  /** Range multiplier per zoom step. Default 2. */
  zoomFactor?: number;
  /** Degrees per tilt step. Default 15. */
  tiltStep?: number;
  showTilt?: boolean;
  /** Where the home button goes; `false` hides it. */
  home?: CameraTarget | false;
  /** Animation length for the home button, in ms. Default 1500. */
  animate?: number;
  className?: string;
}

/** Zoom, north-up, tilt and home buttons.
 * @category Widgets
 */
export function NavigationControls({
  position = 'top-right',
  orientation = 'vertical',
  zoomFactor = 2,
  tiltStep = 15,
  showTilt = true,
  home = { latitude: 0, longitude: 0, range: 2e7, heading: 0, tilt: 0 },
  animate = 1500,
  className,
}: NavigationControlsProps) {
  const camera = useCamera();
  return (
    <Panel
      position={position}
      className={cx('wwui-toolbar', orientation === 'horizontal' && 'wwui-toolbar--horizontal', className)}
      style={{ padding: 6 }}
      role="toolbar"
      aria-label="Globe navigation"
    >
      <button type="button" className="wwui-button" title="Zoom in" aria-label="Zoom in" onClick={() => camera.zoomBy(1 / zoomFactor)}>
        +
      </button>
      <button type="button" className="wwui-button" title="Zoom out" aria-label="Zoom out" onClick={() => camera.zoomBy(zoomFactor)}>
        −
      </button>
      <button type="button" className="wwui-button" title="Reset to north" aria-label="Reset to north" onClick={() => camera.resetNorth()}>
        N
      </button>
      {showTilt ? (
        <>
          <button type="button" className="wwui-button" title="Tilt up" aria-label="Tilt up" onClick={() => camera.tiltBy(tiltStep)}>
            ⤒
          </button>
          <button type="button" className="wwui-button" title="Tilt down" aria-label="Tilt down" onClick={() => camera.tiltBy(-tiltStep)}>
            ⤓
          </button>
        </>
      ) : null}
      {home ? (
        <button type="button" className="wwui-button" title="Home" aria-label="Home" onClick={() => void camera.goTo(home, { duration: animate })}>
          ⌂
        </button>
      ) : null}
    </Panel>
  );
}

// packages/angular/src/lib/ui/navigation-controls.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import type { CameraTarget } from 'worldwind-kit';
import { WwGlobeComponent } from '../globe.component';
import { WwPanelComponent, type WwPanelPosition } from './panel.component';

/** Zoom, north-up, tilt and home buttons.
 * @category Widgets
 */
@Component({
  selector: 'ww-navigation-controls',
  imports: [WwPanelComponent],
  template: `
    <ww-panel [position]="position()" [class]="toolbarClass()" style="padding: 6px" role="toolbar" aria-label="Globe navigation">
      <button type="button" class="wwui-button" title="Zoom in" aria-label="Zoom in" (click)="zoom(1 / zoomFactor())">+</button>
      <button type="button" class="wwui-button" title="Zoom out" aria-label="Zoom out" (click)="zoom(zoomFactor())">−</button>
      <button type="button" class="wwui-button" title="Reset to north" aria-label="Reset to north" (click)="north()">N</button>
      @if (showTilt()) {
        <button type="button" class="wwui-button" title="Tilt up" aria-label="Tilt up" (click)="tilt(tiltStep())">⤒</button>
        <button type="button" class="wwui-button" title="Tilt down" aria-label="Tilt down" (click)="tilt(-tiltStep())">⤓</button>
      }
      @if (home(); as target) {
        <button type="button" class="wwui-button" title="Home" aria-label="Home" (click)="goHome(target)">⌂</button>
      }
    </ww-panel>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwNavigationControlsComponent {
  private readonly globeHost = inject(WwGlobeComponent);

  readonly position = input<WwPanelPosition>('top-right');
  readonly orientation = input<'vertical' | 'horizontal'>('vertical');
  /** Range multiplier per zoom step. */
  readonly zoomFactor = input(2);
  /** Degrees per tilt step. */
  readonly tiltStep = input(15);
  readonly showTilt = input(true);
  /** Where the home button goes; `false` hides it. */
  readonly home = input<CameraTarget | false>({ latitude: 0, longitude: 0, range: 2e7, heading: 0, tilt: 0 });
  /** Animation length for the home button, in ms. */
  readonly animate = input(1500);

  protected readonly toolbarClass = computed(
    () => `wwui-toolbar${this.orientation() === 'horizontal' ? ' wwui-toolbar--horizontal' : ''}`,
  );

  protected zoom(factor: number): void {
    this.globeHost.globe()?.camera.zoomBy(factor);
  }

  protected north(): void {
    this.globeHost.globe()?.camera.resetNorth();
  }

  protected tilt(delta: number): void {
    this.globeHost.globe()?.camera.tiltBy(delta);
  }

  protected goHome(target: CameraTarget): void {
    void this.globeHost.globe()?.camera.goTo(target, { duration: this.animate() });
  }
}
