// examples/angular-demo/src/app.component.ts
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import {
  DAY_MS,
  WORLDWIND_COMPONENTS,
  formatLatLon,
  type CameraTarget,
  type GeoJsonStyleResolver,
  type GlobeController,
  type GlobeOptions,
  type LatLonAlt,
  type LayerAttribution,
  type LayerLegend,
  type PickEvent,
  type PushpinColor,
  type TimeDimension,
} from 'ngx-worldwind';

declare global {
  interface Window {
    /** Exposed for the browser tests and for poking around in devtools. */
    worldwindDemo?: { globe: GlobeController };
  }
}

interface PopupState {
  position: LatLonAlt;
  title: string;
  lines: string[];
}

interface City {
  name: string;
  latitude: number;
  longitude: number;
  pushpin: PushpinColor;
}

/** A few GeoJSON features, styled per feature through the featureStyle resolver. */
const AIRPORTS = {
  type: 'FeatureCollection',
  features: [
    { type: 'Feature', properties: { name: 'JFK', busy: true }, geometry: { type: 'Point', coordinates: [-73.7781, 40.6413] } },
    { type: 'Feature', properties: { name: 'LHR', busy: true }, geometry: { type: 'Point', coordinates: [-0.4543, 51.47] } },
    { type: 'Feature', properties: { name: 'HND', busy: false }, geometry: { type: 'Point', coordinates: [139.7798, 35.5494] } },
    {
      type: 'Feature',
      properties: { name: 'North Atlantic tracks' },
      geometry: { type: 'Polygon', coordinates: [[[-60, 40], [-10, 50], [-10, 60], [-60, 55], [-60, 40]]] },
    },
  ],
};

/** Legend for the airports layer: an inline SVG, so any image URL works. */
const AIRPORT_LEGEND: LayerLegend = {
  url: `data:image/svg+xml;utf8,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" width="150" height="54" font-family="sans-serif" font-size="11" fill="#f1f5f9">` +
      `<circle cx="8" cy="10" r="5" fill="#f59e0b"/><text x="20" y="14">Busy airport</text>` +
      `<circle cx="8" cy="28" r="5" fill="#ffffff"/><text x="20" y="32">Quiet airport</text>` +
      `<rect x="3" y="41" width="10" height="10" fill="rgba(251,191,36,0.3)" stroke="#fbbf24"/><text x="20" y="50">Track area</text></svg>`,
  )}`,
  width: 150,
  height: 54,
};

/** NASA GIBS serves daily MODIS imagery over WMS; the TIME parameter picks the day. */
const GIBS_SERVICE = 'https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi';
const GIBS_CREDIT: LayerAttribution = {
  text: 'NASA GIBS',
  url: 'https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api',
};

interface Station {
  latitude: number;
  longitude: number;
  name: string;
}

/** Deterministic pseudo-random points, so the clustered layer looks the same on every load. */
function samplePoints(count: number, seed: number): Station[] {
  let state = seed >>> 0;
  const random = () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 4294967296;
  };
  const points: Station[] = [];
  for (let i = 0; i < count; i += 1) {
    // Clumped around a few centres so clusters split as you zoom.
    const centre = Math.floor(random() * 12);
    const spread = 4 + (centre % 3) * 6;
    points.push({
      latitude: Math.max(-80, Math.min(80, ((centre * 47) % 140) - 70 + (random() - 0.5) * spread)),
      longitude: ((centre * 97) % 360) - 180 + (random() - 0.5) * spread * 2,
      name: `Station ${i + 1}`,
    });
  }
  return points;
}

/** The last 30 days up to yesterday (GIBS publishes with about a day of latency). */
function recentDays(): TimeDimension {
  const now = new Date();
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() - 1));
  return { start: new Date(end.getTime() - 29 * DAY_MS), end, stepMs: DAY_MS };
}

const CITIES: City[] = [
  { name: 'New York', latitude: 40.7128, longitude: -74.006, pushpin: 'red' },
  { name: 'London', latitude: 51.5074, longitude: -0.1278, pushpin: 'blue' },
  { name: 'Tokyo', latitude: 35.6762, longitude: 139.6503, pushpin: 'green' },
  { name: 'Sydney', latitude: -33.8688, longitude: 151.2093, pushpin: 'orange' },
];

@Component({
  selector: 'app-root',
  imports: [...WORLDWIND_COMPONENTS],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ww-globe [options]="options" style="height: 100vh" (globeClick)="onGlobeClick($event)" (ready)="expose($event)">
      <div wwFallback class="wwui-panel wwui-panel--top-left">Loading NASA WorldWind…</div>

      <ww-layer kind="osm" [enabled]="false" />
      <ww-wms-layer
        [service]="gibsService"
        layerNames="MODIS_Terra_CorrectedReflectance_TrueColor"
        displayName="MODIS Terra (daily)"
        format="image/jpeg"
        [numLevels]="10"
        [enabled]="false"
        [timeDimension]="modisDays"
        [attribution]="gibsCredit"
      />
      <ww-camera
        [latitude]="target().latitude"
        [longitude]="target().longitude"
        [range]="selected() ? 1.5e6 : 1.6e7"
        [animate]="2000"
      />

      <ww-renderable-layer name="Cities">
        @for (city of cities; track city.name) {
          <ww-placemark
            [position]="city"
            [label]="city.name"
            [pushpin]="city.pushpin"
            [highlight]="{ imageScale: 1.4 }"
            [highlightOnHover]="true"
            [userData]="{ name: city.name }"
            (shapeClick)="selected.set(city)"
          />
        }
        <ww-path [positions]="route" stroke="#38bdf8" [strokeWidth]="3" [followTerrain]="false" pathType="greatCircle" />
        @if (selected(); as city) {
          <ww-surface-circle [center]="city" [radius]="150000" fill="rgba(56, 189, 248, 0.25)" stroke="#38bdf8" />
        }
      </ww-renderable-layer>

      <ww-cluster-layer [items]="stations" name="Stations (5,000 clustered)" [radius]="56" (itemClick)="selectedStation.set($event.item.name)" />

      <ww-geojson-layer [source]="airports" name="Airports" [featureStyle]="airportStyle" [legend]="airportLegend" />

      @if (popup(); as p) {
        <ww-popup [position]="p.position" [heading]="p.title" [closable]="true" (closed)="popup.set(null)">
          @for (line of p.lines; track line) {
            <div>{{ line }}</div>
          }
        </ww-popup>
      }

      <ww-goto-box position="top-left" />
      <ww-measure-tool position="top-left" panelClass="wwui-panel--below-goto" />
      <ww-draw-tool position="top-left" panelClass="wwui-panel--below-measure" [showDownload]="true" />
      <ww-layer-switcher position="bottom-right" />
      <ww-navigation-controls position="top-right" [home]="home" [fullscreen]="true" [screenshot]="true" />
      <ww-coordinates position="bottom-left" />
      <ww-projection-switcher position="top-right" panelClass="wwui-panel--beside-nav" />
      <ww-compass position="top-right" panelClass="wwui-panel--below-projection" />
      <ww-time-slider position="bottom-center" panelClass="wwui-panel--above-scale" />
      <ww-legend position="bottom-left" panelClass="wwui-panel--above-status" />
      <ww-scale-bar position="bottom-center" panelClass="wwui-panel--above-attribution" />
      <ww-attribution position="bottom-center" [extra]="credits" />

      <ww-panel position="bottom-left" class="wwui-panel--above-coords">
        <p class="wwui-goto__status" style="margin: 0">{{ status() }}</p>
      </ww-panel>
    </ww-globe>
  `,
})
export class AppComponent {
  readonly cities = CITIES;
  readonly route: LatLonAlt[] = CITIES.map((city) => ({ latitude: city.latitude, longitude: city.longitude, altitude: 300_000 }));
  readonly airports = AIRPORTS;
  readonly airportLegend = AIRPORT_LEGEND;
  readonly gibsService = GIBS_SERVICE;
  readonly gibsCredit = GIBS_CREDIT;
  readonly modisDays = recentDays();
  readonly credits: LayerAttribution[] = [{ text: 'worldwind-ui', url: 'https://github.com/qwertymuzaffar/worldwind-ui' }];
  readonly airportStyle: GeoJsonStyleResolver = ({ properties, geometryType }) =>
    geometryType === 'Point'
      ? { point: { pushpin: properties['busy'] ? 'orange' : 'white', labelProperty: 'name', imageScale: 0.8 } }
      : { polygon: { fill: 'rgba(251, 191, 36, 0.15)', stroke: '#fbbf24', strokeWidth: 2 } };
  readonly options: GlobeOptions = {
    layers: ['blue-marble-landsat', 'atmosphere', 'star-field', 'compass'],
    view: { latitude: 20, longitude: 10, range: 1.6e7 },
  };
  readonly home: CameraTarget = { latitude: 20, longitude: 10, range: 1.6e7, heading: 0, tilt: 0 };

  readonly selected = signal<City | null>(null);
  readonly selectedStation = signal<string | null>(null);
  readonly stations: Station[] = samplePoints(5000, 7);
  readonly lastClick = signal<PickEvent | null>(null);
  readonly popup = signal<PopupState | null>(null);

  expose(globe: GlobeController): void {
    window.worldwindDemo = { globe };
  }

  onGlobeClick(event: PickEvent): void {
    this.lastClick.set(event);
    const data = (event.top?.object as { userProperties?: unknown } | undefined)?.userProperties as Record<string, unknown> | undefined;
    const position = event.top?.position ?? event.position;
    if (!data || !position || typeof data['name'] !== 'string') {
      this.popup.set(null);
      return;
    }
    const lines = [formatLatLon(position, { precision: 3 })];
    if ('busy' in data) lines.push(data['busy'] ? 'Busy airport' : 'Quiet airport');
    this.popup.set({ position, title: data['name'], lines });
  }
  readonly target = computed(() => this.selected() ?? { latitude: 20, longitude: 10 });
  readonly status = computed(() => {
    const selected = this.selected();
    const click = this.lastClick();
    const station = this.selectedStation();
    const base = selected ? `Selected: ${selected.name}` : station ? `Selected: ${station}` : 'Click a pin to fly there';
    return click?.position ? `${base} · last click ${formatLatLon(click.position, { precision: 2 })}` : base;
  });
}

// examples/react-demo/src/App.tsx
import { useState } from 'react';
import {
  Attribution,
  Camera,
  ClusterLayer,
  Compass,
  CoordinatesReadout,
  DAY_MS,
  DrawTool,
  GeoJsonLayer,
  Globe,
  GoToBox,
  Layer,
  LayerSwitcher,
  Legend,
  MeasureTool,
  NavigationControls,
  Panel,
  Path,
  Placemark,
  Popup,
  ProjectionSwitcher,
  RenderableLayer,
  ScaleBar,
  SurfaceCircle,
  TimeSlider,
  WmsLayer,
  formatLatLon,
  type GlobeController,
  type LatLonAlt,
  type PickEvent,
  type TimeDimension,
} from 'react-worldwind';

declare global {
  interface Window {
    /** Exposed for the browser tests and for poking around in devtools. */
    worldwindDemo?: { globe: GlobeController };
  }
}

interface PopupState {
  position: LatLonAlt;
  title: string;
  lines: string[];
}

/** Turns whatever was clicked (a city, an airport feature) into popup content. */
function describePick(event: PickEvent): PopupState | null {
  const data = (event.top?.object as { userProperties?: unknown } | undefined)?.userProperties as Record<string, unknown> | undefined;
  const position = event.top?.position ?? event.position;
  if (!data || !position || typeof data.name !== 'string') return null;
  const lines = [formatLatLon(position, { precision: 3 })];
  if ('busy' in data) lines.push(data.busy ? 'Busy airport' : 'Quiet airport');
  return { position, title: data.name, lines };
}

const CITIES = [
  { name: 'New York', latitude: 40.7128, longitude: -74.006, pushpin: 'red' as const },
  { name: 'London', latitude: 51.5074, longitude: -0.1278, pushpin: 'blue' as const },
  { name: 'Tokyo', latitude: 35.6762, longitude: 139.6503, pushpin: 'green' as const },
  { name: 'Sydney', latitude: -33.8688, longitude: 151.2093, pushpin: 'orange' as const },
];

const ROUTE = CITIES.map((city) => ({ latitude: city.latitude, longitude: city.longitude, altitude: 300_000 }));

/** A few GeoJSON features, styled per feature through the GeoJsonLayer callback. */
const AIRPORTS = {
  type: 'FeatureCollection',
  features: [
    { type: 'Feature', properties: { name: 'JFK', busy: true }, geometry: { type: 'Point', coordinates: [-73.7781, 40.6413] } },
    { type: 'Feature', properties: { name: 'LHR', busy: true }, geometry: { type: 'Point', coordinates: [-0.4543, 51.47] } },
    { type: 'Feature', properties: { name: 'HND', busy: false }, geometry: { type: 'Point', coordinates: [139.7798, 35.5494] } },
    {
      type: 'Feature',
      properties: { name: 'North Atlantic tracks' },
      geometry: { type: 'Polygon', coordinates: [[[-60, 40], [-10, 50], [-10, 60], [-60, 55], [-60, 40]]] },
    },
  ],
};

/** Legend for the airports layer: an inline SVG, so any image URL works. */
const AIRPORT_LEGEND = `data:image/svg+xml;utf8,${encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" width="150" height="54" font-family="sans-serif" font-size="11" fill="#f1f5f9">` +
    `<circle cx="8" cy="10" r="5" fill="#f59e0b"/><text x="20" y="14">Busy airport</text>` +
    `<circle cx="8" cy="28" r="5" fill="#ffffff"/><text x="20" y="32">Quiet airport</text>` +
    `<rect x="3" y="41" width="10" height="10" fill="rgba(251,191,36,0.3)" stroke="#fbbf24"/><text x="20" y="50">Track area</text></svg>`,
)}`;

/** NASA GIBS serves daily MODIS imagery over WMS; the TIME parameter picks the day. */
const GIBS = {
  service: 'https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi',
  layerNames: 'MODIS_Terra_CorrectedReflectance_TrueColor',
  attribution: { text: 'NASA GIBS', url: 'https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api' },
};

/** Deterministic pseudo-random points, so the clustered layer looks the same on every load. */
function samplePoints(count: number, seed: number) {
  let state = seed >>> 0;
  const random = () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 4294967296;
  };
  const points: Array<{ latitude: number; longitude: number; name: string }> = [];
  for (let i = 0; i < count; i += 1) {
    // Clumped around a few centres so clusters split as you zoom.
    const centre = Math.floor(random() * 12);
    const spread = 4 + (centre % 3) * 6;
    points.push({
      latitude: Math.max(-80, Math.min(80, ((centre * 47) % 140) - 70 + (random() - 0.5) * spread)),
      longitude: ((centre * 97) % 360) - 180 + (random() - 0.5) * spread * 2,
      name: `Station ${i + 1}`,
    });
  }
  return points;
}
const SAMPLE_POINTS = samplePoints(5000, 7);

/** The last 30 days up to yesterday (GIBS publishes with about a day of latency). */
function recentDays(): TimeDimension {
  const now = new Date();
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() - 1));
  return { start: new Date(end.getTime() - 29 * DAY_MS), end, stepMs: DAY_MS };
}
const MODIS_DAYS = recentDays();

export function App() {
  const [selected, setSelected] = useState<(typeof CITIES)[number] | null>(null);
  const [lastClick, setLastClick] = useState<PickEvent | null>(null);
  const [popup, setPopup] = useState<PopupState | null>(null);
  const [selectedStation, setSelectedStation] = useState<string | null>(null);
  const target = selected ?? { latitude: 20, longitude: 10 };

  return (
    <Globe
      style={{ height: '100vh' }}
      layers={['blue-marble-landsat', 'atmosphere', 'star-field', 'compass']}
      view={{ latitude: 20, longitude: 10, range: 1.6e7 }}
      fallback={<div className="wwui-panel wwui-panel--top-left">Loading NASA WorldWind…</div>}
      onClick={(event) => {
        setLastClick(event);
        setPopup(describePick(event));
      }}
      onReady={(globe) => {
        window.worldwindDemo = { globe };
      }}
    >
      <Layer kind="osm" enabled={false} />
      <WmsLayer
        service={GIBS.service}
        layerNames={GIBS.layerNames}
        displayName="MODIS Terra (daily)"
        format="image/jpeg"
        numLevels={10}
        enabled={false}
        timeDimension={MODIS_DAYS}
        attribution={GIBS.attribution}
      />
      <Camera latitude={target.latitude} longitude={target.longitude} range={selected ? 1.5e6 : 1.6e7} animate={2000} />

      <RenderableLayer name="Cities">
        {CITIES.map((city) => (
          <Placemark
            key={city.name}
            position={city}
            label={city.name}
            pushpin={city.pushpin}
            highlight={{ imageScale: 1.4 }}
            highlightOnHover
            userData={{ name: city.name }}
            onClick={() => setSelected(city)}
          />
        ))}
        <Path positions={ROUTE} stroke="#38bdf8" strokeWidth={3} followTerrain={false} pathType="greatCircle" />
        {selected ? <SurfaceCircle center={selected} radius={150_000} fill="rgba(56, 189, 248, 0.25)" stroke="#38bdf8" /> : null}
      </RenderableLayer>

      <ClusterLayer items={SAMPLE_POINTS} name="Stations (5,000 clustered)" radius={56} onItemClick={(station) => setSelectedStation(station.name)} />

      <GeoJsonLayer
        source={AIRPORTS}
        name="Airports"
        legend={{ url: AIRPORT_LEGEND, width: 150, height: 54 }}
        style={({ properties, geometryType }) =>
          geometryType === 'Point'
            ? { point: { pushpin: properties.busy ? 'orange' : 'white', labelProperty: 'name', imageScale: 0.8 } }
            : { polygon: { fill: 'rgba(251, 191, 36, 0.15)', stroke: '#fbbf24', strokeWidth: 2 } }
        }
      />

      {popup ? (
        <Popup position={popup.position} title={popup.title} onClose={() => setPopup(null)}>
          {popup.lines.map((line) => (
            <div key={line}>{line}</div>
          ))}
        </Popup>
      ) : null}

      <GoToBox position="top-left" />
      <MeasureTool position="top-left" className="wwui-panel--below-goto" />
      <DrawTool position="top-left" className="wwui-panel--below-measure" showDownload />
      <LayerSwitcher position="bottom-right" />
      <NavigationControls position="top-right" home={{ latitude: 20, longitude: 10, range: 1.6e7, heading: 0, tilt: 0 }} fullscreen screenshot />
      <CoordinatesReadout position="bottom-left" />
      <ProjectionSwitcher position="top-right" className="wwui-panel--beside-nav" />
      <Compass position="top-right" className="wwui-panel--below-projection" />
      <TimeSlider position="bottom-center" className="wwui-panel--above-scale" />
      <Legend position="bottom-left" className="wwui-panel--above-status" />
      <ScaleBar position="bottom-center" className="wwui-panel--above-attribution" />
      <Attribution position="bottom-center" extra={[{ text: 'worldwind-ui', url: 'https://github.com/qwertymuzaffar/worldwind-ui' }]} />

      <Panel position="bottom-left" className="wwui-panel--above-coords">
        <p className="wwui-goto__status" style={{ margin: 0 }}>
          {selected ? `Selected: ${selected.name}` : selectedStation ? `Selected: ${selectedStation}` : 'Click a pin to fly there'}
          {lastClick?.position ? ` · last click ${formatLatLon(lastClick.position, { precision: 2 })}` : ''}
        </p>
      </Panel>
    </Globe>
  );
}
