// packages/react/src/Globe.tsx
import { useEffect, useRef, useState, type CSSProperties, type ReactNode, type RefObject } from 'react';
import {
  GlobeController,
  ShapeEventRegistry,
  type GlobeOptions,
  type LoadWorldWindOptions,
  type PickEventType,
  type PickHandler,
  type ProjectionKind,
} from 'worldwind-kit';
import { GlobeContext, type GlobeContextValue } from './context';
import { cx, useLatest } from './internal/utils';

/** @category Globe */
export interface GlobeProps extends Omit<GlobeOptions, 'projection'> {
  /** Reactive: changing it switches projection on the live globe. */
  projection?: ProjectionKind;
  className?: string;
  style?: CSSProperties;
  /** Rendered while WorldWind loads. */
  fallback?: ReactNode;
  loadOptions?: LoadWorldWindOptions;
  onReady?: (globe: GlobeController) => void;
  onError?: (error: unknown) => void;
  onClick?: PickHandler;
  onDoubleClick?: PickHandler;
  onHover?: PickHandler;
  children?: ReactNode;
}

function usePickSubscription(globe: GlobeController | null, type: PickEventType, handler: PickHandler | undefined) {
  const latest = useLatest(handler);
  const active = handler !== undefined;
  useEffect(() => {
    if (!globe || !active) return;
    return globe.on(type, (event) => latest.current?.(event));
  }, [globe, type, active, latest]);
}

/** What the globe is created with: read once, at mount, from the latest props. */
interface GlobeInit {
  options: GlobeOptions;
  loadOptions?: LoadWorldWindOptions;
  onReady?: (globe: GlobeController) => void;
  onError?: (error: unknown) => void;
}

/**
 * Creates the globe in the host element once and destroys it on unmount. A creation that
 * resolves after unmount is destroyed straight away; a rejection surfaces as `error`.
 */
function useGlobeController(
  hostRef: RefObject<HTMLDivElement | null>,
  init: GlobeInit,
): { value: GlobeContextValue | null; error: unknown } {
  const latest = useLatest(init);
  const [value, setValue] = useState<GlobeContextValue | null>(null);
  const [error, setError] = useState<unknown>(null);

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    let cancelled = false;
    let controller: GlobeController | null = null;
    let registry: ShapeEventRegistry | null = null;
    const { options, loadOptions } = latest.current;

    GlobeController.create(host, options, loadOptions).then(
      (globe) => {
        if (cancelled) {
          globe.destroy();
          return;
        }
        controller = globe;
        registry = new ShapeEventRegistry(globe);
        setValue({ globe, shapeEvents: registry });
        latest.current.onReady?.(globe);
      },
      (reason: unknown) => {
        if (cancelled) return;
        setError(reason);
        latest.current.onError?.(reason);
      },
    );

    return () => {
      cancelled = true;
      registry?.destroy();
      controller?.destroy();
      setValue(null);
    };
  }, [hostRef, latest]);

  return { value, error };
}

/** Switches the live globe's projection whenever the prop changes. */
function useProjectionSync(globe: GlobeController | null, projection: ProjectionKind | undefined) {
  useEffect(() => {
    if (globe && projection && globe.projection !== projection) globe.setProjection(projection);
  }, [globe, projection]);
}

/** The globe-wide pick handlers; each subscription is active only while its prop is set. */
function usePickHandlers(
  globe: GlobeController | null,
  { onClick, onDoubleClick, onHover }: Pick<GlobeProps, 'onClick' | 'onDoubleClick' | 'onHover'>,
) {
  usePickSubscription(globe, 'click', onClick);
  usePickSubscription(globe, 'dblclick', onDoubleClick);
  usePickSubscription(globe, 'hover', onHover);
}

function ErrorPanel({ message }: { message: string }) {
  return (
    <div className="wwui-overlay">
      <div className="wwui-panel wwui-panel--top-left" role="alert">
        {message}
      </div>
    </div>
  );
}

/**
 * Renders a WorldWind globe. Creation options (`layers`, `view`, `elevation`, ...) apply on
 * mount; `projection` and the event handlers are reactive. Children render inside an overlay
 * above the canvas once the globe is ready, with the globe available through context.
 *
 * Give the element a height (via `className` or `style`); the canvas fills it.
  * @example
 * ```tsx
 * <Globe style={{ height: 480 }} layers={['blue-marble-landsat', 'atmosphere']} view={{ latitude: 40, longitude: -74, range: 2e6 }}>
 *   <RenderableLayer name="Cities">
 *     <Placemark position={{ latitude: 40.7128, longitude: -74.006 }} label="New York" />
 *   </RenderableLayer>
 *   <LayerSwitcher />
 * </Globe>
 * ```
 * @category Globe
 */
export function Globe(props: GlobeProps) {
  const {
    projection,
    className,
    style,
    fallback,
    loadOptions,
    onReady,
    onError,
    onClick,
    onDoubleClick,
    onHover,
    children,
    ...creationOptions
  } = props;

  const hostRef = useRef<HTMLDivElement>(null);
  const options = { ...creationOptions, projection };
  const { value, error } = useGlobeController(hostRef, { options, loadOptions, onReady, onError });
  const globe = value?.globe ?? null;
  useProjectionSync(globe, projection);
  usePickHandlers(globe, { onClick, onDoubleClick, onHover });

  const message = error instanceof Error ? error.message : error != null ? String(error) : null;

  return (
    <div className={cx('wwui-globe', className)} style={{ position: 'relative', ...style }}>
      <div ref={hostRef} className="wwui-globe__canvas" style={{ position: 'absolute', inset: 0 }} />
      {value ? (
        <GlobeContext.Provider value={value}>
          <div className="wwui-overlay">{children}</div>
        </GlobeContext.Provider>
      ) : fallback != null && message == null ? (
        <div className="wwui-overlay">{fallback}</div>
      ) : null}
      {message != null ? <ErrorPanel message={message} /> : null}
    </div>
  );
}

// packages/angular/src/lib/globe.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  afterNextRender,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import {
  GlobeController,
  ShapeEventRegistry,
  type CameraState,
  type GlobeOptions,
  type LoadWorldWindOptions,
  type PickEvent,
  type PickResult,
  type ProjectionKind,
  type WWLayer,
} from 'worldwind-kit';

/**
 * Renders a WorldWind globe. `options` apply on creation; `projection` is reactive. Project
 * layer, shape and widget components inside it; content marked `wwFallback` shows while
 * WorldWind loads.
 *
 * ```html
 * <ww-globe [options]="{ layers: ['blue-marble-landsat', 'atmosphere'] }" style="height: 480px">
 *   <span wwFallback>Loading…</span>
 *   <ww-layer-switcher />
 * </ww-globe>
 * ```
  * @category Globe
 */
@Component({
  selector: 'ww-globe',
  template: `
    <div #host class="wwui-globe__canvas" style="position: absolute; inset: 0"></div>
    @if (globe()) {
      <div class="wwui-overlay"><ng-content /></div>
    } @else if (errorMessage(); as message) {
      <div class="wwui-overlay">
        <div class="wwui-panel wwui-panel--top-left" role="alert">{{ message }}</div>
      </div>
    } @else {
      <div class="wwui-overlay"><ng-content select="[wwFallback]" /></div>
    }
  `,
  host: { class: 'wwui-globe', style: 'display: block; position: relative' },
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwGlobeComponent {
  /** Creation options (layers, view, elevation, asset URL, ...). Applied once. */
  readonly options = input<GlobeOptions>({});
  /** Reactive projection switch. */
  readonly projection = input<ProjectionKind | undefined>(undefined);
  readonly loadOptions = input<LoadWorldWindOptions | undefined>(undefined);
  /**
   * Pick under the mouse on every frame and expose it as `hoverPick` / `globeHover`.
   * Off by default because picking costs GPU time; widgets that need it turn it on themselves.
   */
  readonly hoverPicking = input(false);

  readonly ready = output<GlobeController>();
  readonly loadError = output<unknown>();
  readonly globeClick = output<PickEvent>();
  readonly globeDoubleClick = output<PickEvent>();
  readonly globeHover = output<PickEvent>();

  /** The controller, null until WorldWind has loaded. */
  readonly globe = signal<GlobeController | null>(null);
  readonly error = signal<unknown>(null);
  readonly errorMessage = computed(() => {
    const error = this.error();
    return error == null ? null : error instanceof Error ? error.message : String(error);
  });
  /** Camera state, updated after each frame in which it changed. */
  readonly cameraState = signal<CameraState | null>(null);
  /** Layers bottom to top, updated on every change. */
  readonly layers = signal<readonly WWLayer[]>([]);
  /** Latest hover pick while hover picking is active. */
  readonly hoverPick = signal<PickResult | null>(null);
  /** The current projection, updated whenever it changes. */
  readonly projectionState = signal<ProjectionKind>('3d');

  private readonly host = viewChild.required<ElementRef<HTMLDivElement>>('host');
  private registry: ShapeEventRegistry | null = null;
  private hoverUsers = 0;
  private releaseHover: (() => void) | null = null;
  private destroyed = false;

  constructor() {
    afterNextRender(() => {
      void this.init();
    });
    effect(() => {
      const projection = this.projection();
      const globe = this.globe();
      if (globe && projection && globe.projection !== projection) globe.setProjection(projection);
    });
    effect((onCleanup) => {
      if (!this.hoverPicking() || !this.globe()) return;
      const release = untracked(() => this.acquireHover());
      onCleanup(release);
    });
    inject(DestroyRef).onDestroy(() => this.dispose());
  }

  /** Routes picks to shape components. Available once the globe is ready. */
  get shapeEvents(): ShapeEventRegistry {
    if (!this.registry) throw new Error('ngx-worldwind: the globe is not ready yet.');
    return this.registry;
  }

  /** Turns hover picking on until the returned function is called (reference counted). */
  acquireHover(): () => void {
    this.hoverUsers += 1;
    const globe = this.globe();
    if (this.hoverUsers === 1 && globe) {
      this.releaseHover = globe.on('hover', (event) => {
        if (this.destroyed) return;
        this.hoverPick.set(event);
        this.globeHover.emit(event);
      });
    }
    let released = false;
    return () => {
      if (released) return;
      released = true;
      this.hoverUsers -= 1;
      if (this.hoverUsers === 0) {
        this.releaseHover?.();
        this.releaseHover = null;
      }
    };
  }

  private async init(): Promise<void> {
    try {
      const globe = await GlobeController.create(this.host().nativeElement, this.options(), this.loadOptions());
      if (this.destroyed) {
        globe.destroy();
        return;
      }
      this.registry = new ShapeEventRegistry(globe);
      globe.on('click', (event) => {
        if (!this.destroyed) this.globeClick.emit(event);
      });
      globe.on('dblclick', (event) => {
        if (!this.destroyed) this.globeDoubleClick.emit(event);
      });
      globe.camera.subscribe((state) => this.cameraState.set(state));
      globe.layers.subscribe((change) => this.layers.set(change.layers));
      globe.onProjectionChange((projection) => this.projectionState.set(projection));
      this.cameraState.set(globe.camera.get());
      this.layers.set(globe.layers.all);
      this.projectionState.set(globe.projection);
      this.globe.set(globe);
      this.ready.emit(globe);
    } catch (error) {
      if (this.destroyed) return;
      this.error.set(error);
      this.loadError.emit(error);
    }
  }

  private dispose(): void {
    this.destroyed = true;
    this.releaseHover?.();
    this.registry?.destroy();
    this.globe()?.destroy();
  }
}
