// packages/react/src/layers.tsx
import { useEffect, type DependencyList, type ReactNode } from 'react';
import {
  createBuiltInLayer,
  createWmsLayer,
  createWmsLayerFromCapabilities,
  createWmtsLayerFromCapabilities,
  loadGeoJson,
  loadKml,
  type BuiltInLayerKind,
  type GeoJsonStyle,
  type GeoJsonStyleResolver,
  type GlobeController,
  type LayerOptions,
  type WWLayer,
  type WWRenderableLayer,
  type WmsLayerOptions,
  type WmtsLayerFromCapabilitiesOptions,
} from 'worldwind-kit';
import { useGlobe } from './context';
import { useLatest } from './internal/utils';
import { RenderableLayerContext } from './context';
import { useLayer, type UseLayerOptions } from './hooks';

export interface LayerProps extends UseLayerOptions {
  /** One of WorldWind's built-in layers, e.g. `blue-marble-landsat`, `osm`, `atmosphere`, `compass`. */
  kind: BuiltInLayerKind;
}

/** Adds a built-in WorldWind layer. Changing `kind` recreates it. */
export function Layer({ kind, ...options }: LayerProps) {
  useLayer((globe) => createBuiltInLayer(globe.worldWind, globe.wwd, kind), [kind], options);
  return null;
}

export interface WmsLayerProps extends WmsLayerOptions {
  index?: number;
  /**
   * Read the sector, formats and tiling from the service's GetCapabilities document instead of
   * the props; `layerNames` is then the single layer name to look up.
   */
  fromCapabilities?: boolean;
  onError?: (error: unknown) => void;
}

/** Adds an OGC WMS layer. Changing the service configuration recreates it. */
export function WmsLayer(props: WmsLayerProps) {
  const {
    index,
    displayName,
    enabled,
    opacity,
    pickEnabled,
    minActiveAltitude,
    maxActiveAltitude,
    fromCapabilities,
    onError,
    ...config
  } = props;
  const configKey = JSON.stringify({ ...config, fromCapabilities });
  useLayer(
    (globe) =>
      fromCapabilities
        ? createWmsLayerFromCapabilities(globe.worldWind, {
            service: config.service,
            layer: config.layerNames,
            time: config.time,
            displayName,
          })
        : createWmsLayer(globe.worldWind, { ...config, displayName }),
    [configKey],
    { index, displayName, enabled, opacity, pickEnabled, minActiveAltitude, maxActiveAltitude, onError },
  );
  return null;
}

export interface WmtsLayerProps extends Omit<WmtsLayerFromCapabilitiesOptions, 'fetch' | 'signal'> {
  index?: number;
  onError?: (error: unknown) => void;
}

/** Adds an OGC WMTS layer, configured from the service's GetCapabilities document. */
export function WmtsLayer(props: WmtsLayerProps) {
  const {
    index,
    displayName,
    enabled,
    opacity,
    pickEnabled,
    minActiveAltitude,
    maxActiveAltitude,
    onError,
    ...source
  } = props;
  const sourceKey = JSON.stringify(source);
  useLayer(
    (globe) => createWmtsLayerFromCapabilities(globe.worldWind, { ...source, displayName }),
    [sourceKey],
    { index, displayName, enabled, opacity, pickEnabled, minActiveAltitude, maxActiveAltitude, onError },
  );
  return null;
}

export interface GeoJsonLayerProps extends UseLayerOptions {
  /** A URL, a JSON string, or a GeoJSON object. */
  source: string | object;
  style?: GeoJsonStyle | GeoJsonStyleResolver;
  /** Shown in layer switchers. */
  name?: string;
  onLoad?: (layer: WWRenderableLayer) => void;
}

/** Loads GeoJSON into its own renderable layer; reloads when `source` or `style` change. */
export function GeoJsonLayer({ source, style, name = 'GeoJSON', onLoad, onError, ...options }: GeoJsonLayerProps) {
  const globe = useGlobe();
  const layer = useLayer<WWRenderableLayer>((g) => new g.worldWind.RenderableLayer(name), [], { displayName: name, ...options });
  const latest = useLatest({ style, onLoad, onError });
  const sourceKey = typeof source === 'string' ? source : JSON.stringify(source);
  const styleKey = typeof style === 'function' ? 'fn' : JSON.stringify(style ?? null);

  useEffect(() => {
    if (!layer) return;
    let cancelled = false;
    const controller = new AbortController();
    layer.removeAllRenderables();
    loadGeoJson(globe.worldWind, source, layer, { style: latest.current.style, signal: controller.signal }).then(
      () => {
        if (cancelled) return;
        globe.redraw();
        latest.current.onLoad?.(layer);
      },
      (error: unknown) => {
        if (!cancelled) (latest.current.onError ?? console.error)(error);
      },
    );
    return () => {
      cancelled = true;
      controller.abort();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [globe, layer, sourceKey, styleKey, latest]);
  return null;
}

export interface KmlLayerProps extends UseLayerOptions {
  url: string;
  name?: string;
  onLoad?: (document: unknown) => void;
}

/** Loads a KML or KMZ document into its own renderable layer. */
export function KmlLayer({ url, name = 'KML', onLoad, onError, ...options }: KmlLayerProps) {
  const globe = useGlobe();
  const layer = useLayer<WWRenderableLayer>((g) => new g.worldWind.RenderableLayer(name), [], { displayName: name, ...options });
  const latest = useLatest({ onLoad, onError });

  useEffect(() => {
    if (!layer) return;
    let cancelled = false;
    layer.removeAllRenderables();
    loadKml(globe.worldWind, url, layer).then(
      (document) => {
        if (cancelled) return;
        globe.redraw();
        latest.current.onLoad?.(document);
      },
      (error: unknown) => {
        if (!cancelled) (latest.current.onError ?? console.error)(error);
      },
    );
    return () => {
      cancelled = true;
    };
  }, [globe, layer, url, latest]);
  return null;
}

export interface RenderableLayerProps extends UseLayerOptions {
  /** Shown in layer switchers. */
  name?: string;
  children?: ReactNode;
}

/** A layer that holds shapes: render `<Placemark>`, `<Path>`, `<Polygon>` and friends inside it. */
export function RenderableLayer({ name = 'Renderables', children, ...options }: RenderableLayerProps) {
  const layer = useLayer<WWRenderableLayer>(
    (globe) => new globe.worldWind.RenderableLayer(name),
    [],
    { displayName: name, ...options },
  );
  if (!layer) return null;
  return <RenderableLayerContext.Provider value={layer}>{children}</RenderableLayerContext.Provider>;
}

export interface CustomLayerProps<L extends WWLayer> extends UseLayerOptions {
  /** Builds any WorldWind layer, e.g. `new globe.worldWind.WmtsLayer(config)`. */
  create: (globe: GlobeController) => L;
  /** Recreate the layer when these change. */
  deps?: DependencyList;
  children?: (layer: L) => ReactNode;
}

/** Escape hatch for layers the library has no component for. */
export function CustomLayer<L extends WWLayer>({ create, deps = [], children, ...options }: CustomLayerProps<L>) {
  const layer = useLayer(create, deps, options);
  return layer && children ? <>{children(layer)}</> : null;
}

export type { LayerOptions };

// packages/angular/src/lib/layers.ts
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
} from '@angular/core';
import {
  applyLayerOptions,
  createBuiltInLayer,
  createWmsLayer,
  createWmsLayerFromCapabilities,
  createWmtsLayerFromCapabilities,
  loadGeoJson,
  loadKml,
  type BuiltInLayerKind,
  type GeoJsonStyle,
  type GeoJsonStyleResolver,
  type GlobeController,
  type LayerOptions,
  type SectorInput,
  type WWLayer,
  type WWRenderableLayer,
} from 'worldwind-kit';
import { WwGlobeComponent } from './globe.component';

/** Shared inputs and lifecycle for layer components. Subclasses implement `create`. */
@Directive()
export abstract class WwLayerBase<L extends WWLayer = WWLayer> {
  protected readonly globeHost = inject(WwGlobeComponent);

  /** Position in the layer stack (0 = bottom). Creation only. */
  readonly index = input<number | undefined>(undefined);
  readonly displayName = input<string | undefined>(undefined);
  readonly enabled = input<boolean | undefined>(undefined);
  readonly opacity = input<number | undefined>(undefined);
  readonly pickEnabled = input<boolean | undefined>(undefined);
  readonly minActiveAltitude = input<number | undefined>(undefined);
  readonly maxActiveAltitude = input<number | undefined>(undefined);

  /** Emits when an asynchronous `create` rejects. */
  readonly loadError = output<unknown>();

  /** The live WorldWind layer, null until the globe is ready (and, for async layers, loaded). */
  readonly layer = signal<L | null>(null);

  private readonly layerOptions = computed<LayerOptions>(() => ({
    displayName: this.displayName(),
    enabled: this.enabled(),
    opacity: this.opacity(),
    pickEnabled: this.pickEnabled(),
    minActiveAltitude: this.minActiveAltitude(),
    maxActiveAltitude: this.maxActiveAltitude(),
  }));

  constructor() {
    effect((onCleanup) => {
      const globe = this.globeHost.globe();
      if (!globe) return;
      let cancelled = false;
      let added: L | null = null;
      const attach = (layer: L) => {
        untracked(() => {
          applyLayerOptions(layer, this.layerOptions());
          globe.layers.add(layer, { index: this.index() });
          added = layer;
          this.layer.set(layer);
        });
      };
      const result = this.create(globe);
      if (result instanceof Promise) {
        result.then(
          (layer) => {
            if (!cancelled) attach(layer);
          },
          (error: unknown) => {
            if (!cancelled) this.loadError.emit(error);
          },
        );
      } else {
        attach(result);
      }
      onCleanup(() => {
        cancelled = true;
        if (added && !globe.isDisposed) globe.layers.remove(added);
        this.layer.set(null);
      });
    });
    effect(() => {
      const layer = this.layer();
      const options = this.layerOptions();
      if (!layer) return;
      untracked(() => {
        const globe = this.globeHost.globe();
        if (globe && !globe.isDisposed) globe.layers.update(layer, options);
      });
    });
  }

  /** Builds the layer, synchronously or from a promise. Signal inputs read here recreate the layer when they change. */
  protected abstract create(globe: GlobeController): L | Promise<L>;
}

/** One of WorldWind's built-in layers: `<ww-layer kind="blue-marble-landsat" />`. */
@Component({
  selector: 'ww-layer',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwLayerComponent extends WwLayerBase {
  readonly kind = input.required<BuiltInLayerKind>();

  protected override create(globe: GlobeController): WWLayer {
    return createBuiltInLayer(globe.worldWind, globe.wwd, this.kind());
  }
}

/** An OGC WMS layer. */
@Component({
  selector: 'ww-wms-layer',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwWmsLayerComponent extends WwLayerBase {
  readonly service = input.required<string>();
  readonly layerNames = input.required<string>();
  /** Read the tiling and formats from GetCapabilities; `layerNames` is then the layer name to look up. */
  readonly fromCapabilities = input(false);
  readonly styleNames = input<string | undefined>(undefined);
  readonly format = input<string | undefined>(undefined);
  readonly size = input<number | undefined>(undefined);
  readonly numLevels = input<number | undefined>(undefined);
  readonly sector = input<SectorInput | undefined>(undefined);
  readonly levelZeroDelta = input<number | undefined>(undefined);
  readonly coordinateSystem = input<string | undefined>(undefined);
  readonly version = input<string | undefined>(undefined);
  readonly time = input<string | null | undefined>(undefined);

  protected override create(globe: GlobeController): WWLayer | Promise<WWLayer> {
    if (this.fromCapabilities()) {
      return createWmsLayerFromCapabilities(globe.worldWind, {
        service: this.service(),
        layer: this.layerNames(),
        time: this.time(),
        displayName: untracked(this.displayName),
      });
    }
    return createWmsLayer(globe.worldWind, {
      service: this.service(),
      layerNames: this.layerNames(),
      styleNames: this.styleNames(),
      format: this.format(),
      size: this.size(),
      numLevels: this.numLevels(),
      sector: this.sector(),
      levelZeroDelta: this.levelZeroDelta(),
      coordinateSystem: this.coordinateSystem(),
      version: this.version(),
      time: this.time(),
      displayName: untracked(this.displayName),
    });
  }
}

/** A layer for shapes. Put `<ww-placemark>`, `<ww-path>` and friends inside it. */
@Component({
  selector: 'ww-renderable-layer',
  template: '<ng-content />',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwRenderableLayerComponent extends WwLayerBase<WWRenderableLayer> {
  readonly name = input('Renderables');

  protected override create(globe: GlobeController): WWRenderableLayer {
    return new globe.worldWind.RenderableLayer(this.name());
  }
}

/** Escape hatch: `<ww-custom-layer [factory]="makeLayer" />` for any WorldWind layer. */
@Component({
  selector: 'ww-custom-layer',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwCustomLayerComponent extends WwLayerBase {
  readonly factory = input.required<(globe: GlobeController) => WWLayer>();

  protected override create(globe: GlobeController): WWLayer {
    return this.factory()(globe);
  }
}

/** An OGC WMTS layer configured from the service's GetCapabilities document. */
@Component({
  selector: 'ww-wmts-layer',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwWmtsLayerComponent extends WwLayerBase {
  /** The WMTS endpoint or a full GetCapabilities URL. */
  readonly service = input.required<string>();
  /** The layer identifier as listed in the capabilities. */
  readonly layer_ = input.required<string>({ alias: 'layer' });
  /** Style identifier (named `styleName` because `style` is the DOM attribute). */
  readonly styleName = input<string | undefined>(undefined);
  readonly matrixSet = input<string | undefined>(undefined);
  readonly format = input<string | undefined>(undefined);
  readonly time = input<string | null | undefined>(undefined);

  protected override create(globe: GlobeController): Promise<WWLayer> {
    return createWmtsLayerFromCapabilities(globe.worldWind, {
      service: this.service(),
      layer: this.layer_(),
      style: this.styleName(),
      matrixSet: this.matrixSet(),
      format: this.format(),
      time: this.time(),
      displayName: untracked(this.displayName),
    });
  }
}

/** Loads GeoJSON into its own renderable layer; reloads when `source` or `style` change. */
@Component({
  selector: 'ww-geojson-layer',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwGeoJsonLayerComponent extends WwLayerBase<WWRenderableLayer> {
  /** A URL, a JSON string, or a GeoJSON object. */
  readonly source = input.required<string | object>();
  /** Per-geometry styling (named `featureStyle` because `style` is the DOM attribute). */
  readonly featureStyle = input<GeoJsonStyle | GeoJsonStyleResolver | undefined>(undefined);
  readonly name = input('GeoJSON');
  readonly loaded = output<WWRenderableLayer>();

  constructor() {
    super();
    effect((onCleanup) => {
      const layer = this.layer();
      const source = this.source();
      const style = this.featureStyle();
      const globe = untracked(this.globeHost.globe);
      if (!layer || !globe) return;
      let cancelled = false;
      const controller = new AbortController();
      layer.removeAllRenderables();
      loadGeoJson(globe.worldWind, source, layer, { style, signal: controller.signal }).then(
        () => {
          if (cancelled) return;
          globe.redraw();
          this.loaded.emit(layer);
        },
        (error: unknown) => {
          if (!cancelled) this.loadError.emit(error);
        },
      );
      onCleanup(() => {
        cancelled = true;
        controller.abort();
      });
    });
  }

  protected override create(globe: GlobeController): WWRenderableLayer {
    return new globe.worldWind.RenderableLayer(this.name());
  }
}

/** Loads a KML or KMZ document into its own renderable layer. */
@Component({
  selector: 'ww-kml-layer',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WwKmlLayerComponent extends WwLayerBase<WWRenderableLayer> {
  readonly url = input.required<string>();
  readonly name = input('KML');
  readonly loaded = output<unknown>();

  constructor() {
    super();
    effect((onCleanup) => {
      const layer = this.layer();
      const url = this.url();
      const globe = untracked(this.globeHost.globe);
      if (!layer || !globe) return;
      let cancelled = false;
      layer.removeAllRenderables();
      loadKml(globe.worldWind, url, layer).then(
        (document) => {
          if (cancelled) return;
          globe.redraw();
          this.loaded.emit(document);
        },
        (error: unknown) => {
          if (!cancelled) this.loadError.emit(error);
        },
      );
      onCleanup(() => {
        cancelled = true;
      });
    });
  }

  protected override create(globe: GlobeController): WWRenderableLayer {
    return new globe.worldWind.RenderableLayer(this.name());
  }
}
